# These are supported funding model platforms

patreon: thepinsteam # Replace with a single Patreon username
ko_fi: thepinsteam # Replace with a single Ko-fi username
liberapay: thepinsteam # Replace with a single Liberapay username
