# This is where our global variables and workflow rules are being set. Usually, this configuration is
# loaded through the include keyword in the main .gitlab-ci.yml file at repository root.

variables:
  DOCKERVERSION: "20.10.8"
  DOCKER_CLI_EXPERIMENTAL: enabled
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'

before_script:
  - apk add bash coreutils gettext curl jq
  - ./scripts/gitlab-cicd-setup.sh