dangerjs:
  stage: triage
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/node:16-alpine
  variables:
    SKIP_LOGIN_STEP: "1"
  before_script:
    - yarn install 
  script:
    - ./scripts/triageops-dangerjs.sh
  rules:
    # Only run DangerJS on merge requests
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
