name: "Docker Image Builder::mkdocs-material"

on:
  push:
    branches:
      - master

env:
  gh_namespace: thepinsteam-customimagebuilds
  # since our RHQCR and Docker Hub namespaces are same,
  # we can just squash them into one env.
  docker_namespace: madebythepinshub
  context_0: build/mkdocs-material
  context_1: liveserver/mkdocs-material

jobs:
  build-image:
    # Ensure test job passes before pushing image.
    name: Build mkdocs-material images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login with Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_ACCESS_KEY }}
      - name: Login with GHCR
        uses: docker/login-action@v1
        with:
          username: RecapTimeBot
          password: ${{ secrets.GH_SERVICE_ACCOUNT_API_KEY }}
          registry: ghcr.io
      - name: Login with RHQCR
        uses: docker/login-action@v1
        with:
          username: madebythepinshub+github_actions
          password: ${{ secrets.RHQCR_SERVICE_ACCOUNT_KEY }}
          registry: quay.io

      - name: Get files changed
        uses: dorny/paths-filter@eb75a1edc117d3756a18ef89958ee59f9500ba58
        id: filter
        with:
          # Base branch used to get changed files
          base: 'master'

          # Enables setting an output in the format in `${FILTERl_NAME}_files
          # with the names of the matching files formatted as JSON array
          list-files: json

          # Returns list of changed files matching each filter
          filters: |
            liveserver:
              - 'liveserver/mkdocs-material/**'
            main:
              - 'build/mkdocs-material/**"
            manualTrigger:
              - '.trigger-build'

      - name: Generate matadata from main
        if: ${{ steps.filter.outputs.main == 'true' || steps.filter.outputs.manualTrigger == 'true' }}
        uses: docker/metadata-action@v3
        id: metadata-main
        with:
          images: |
            ghcr.io/${{ env.gh_namespace }}/${{ env.image_name }}
            quay.io/${{ env.docker_namespace }}/${{ env.image_name }}
            ${{ env.docker_namespace }}/${{ env.image_name }}
          tags: |
            type=sha,format=long
          flavor: |
            latest=true
      - name: "Build the image [main]"
        if: ${{ steps.filter.outputs.main == 'true' || steps.filter.outputs.manualTrigger == 'true' }}
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.context_0 }}
          tags: ${{ steps.metadata-main.outputs.tags }}
          push: true

      - name: Generate matadata from liveserver
        if: ${{ steps.filter.outputs.liveserver == 'true' || steps.filter.outputs.manualTrigger == 'true' }}
        uses: docker/metadata-action@v3
        id: metadata-live
        with:
          images: |
            ghcr.io/${{ env.gh_namespace }}/${{ env.image_name }}
            quay.io/${{ env.docker_namespace }}/${{ env.image_name }}
            ${{ env.docker_namespace }}/${{ env.image_name }}
          tags: |
            type=sha,format=long
            liveserver
          flavor: |
            latest=false

      - name: Preview values first (liveserver)
        run: "echo -e $RESULT_METADATA_GENERATOR"
        if: ${{ steps.filter.outputs.liveserver == 'true' || steps.filter.outputs.manualTrigger == 'true' }}
        env:
          RESULT_METADATA_GENERATOR: ${{ fromJSON(steps.metadata-live.outputs) }}

      - name: "Build the image [liveserver]"
        if: ${{ steps.filter.outputs.liveserver == 'true' || steps.filter.outputs.manualTrigger == 'true' }}
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.context_1 }}
          tags: ${{ steps.metadata-live.outputs.tags }}
          push: true

