name: "Docker Image Builder::mkdocs-material"

on:
  push:
    branches:
      - master

env:
  gh_namespace: thepinsteam-customimagebuilds
  # since our RHQCR and Docker Hub namespaces are same,
  # we can just squash them into one env.
  docker_namespace: madebythepinshub

jobs:
  build-image:
    name: Build mkdocs-material image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get files changed
        uses: dorny/paths-filter@v2
        id: filter
        with:
          # Base branch used to get changed files
          # TODO: Rename to main soon
          base: 'master'

          # Enables setting an output in the format in `${FILTERl_NAME}_files
          # with the names of the matching files formatted as JSON array
          list-files: json

          # Returns list of changed files matching each filter
          filters: |
            dockerfile:
              - 'docker/mkdocs-material/**'
            manual:
              - '.trigger-rebuild'
              - '.github/workflows/docker-ci.yml'

      # Login step
      - name: Login with Docker Hub
        if: ${{ steps.filter.outputs.dockerfile == 'true' || steps.filter.outputs.manual == 'true' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_ACCESS_KEY }}
      - name: Login with GHCR
        if: ${{ steps.filter.outputs.dockerfile == 'true' || steps.filter.outputs.manual == 'true' }}
        uses: docker/login-action@v1
        with:
          username: RecapTimeBot
          password: ${{ secrets.GH_SERVICE_ACCOUNT_API_KEY }}
          registry: ghcr.io
      - name: Login with RHQCR
        if: ${{ steps.filter.outputs.dockerfile == 'true' || steps.filter.outputs.manual == 'true' }}
        uses: docker/login-action@v1
        with:
          username: madebythepinshub+github_actions
          password: ${{ secrets.RHQCR_SERVICE_ACCOUNT_KEY }}
          registry: quay.io

      - name: Generate matadata
        if: ${{ steps.filter.outputs.dockerfile == 'true' || steps.filter.outputs.manual == 'true' }}
        uses: docker/metadata-action@v3
        id: metadata
        with:
          images: |
            ghcr.io/${{ env.gh_namespace }}/${{ env.image_name }}
            quay.io/${{ env.docker_namespace }}/${{ env.image_name }}
            ${{ env.docker_namespace }}/${{ env.image_name }}
          tags: |
            type=sha,format=long
          flavor: |
            latest=true

      - name: "Build the image"
        if: ${{ steps.filter.outputs.dockerfile == 'true' || steps.filter.outputs.manual == 'true' }}
        uses: docker/build-push-action@v2
        with:
          context: docker/mkdocs-material
          tags: ${{ steps.metadata-main.outputs.tags }}
          push: true
