name: Mirror to GitLab SaaS

on:
  push:
    branches: [master]

env:
  gitlab_saas_repo_id: 29726997
  gitlab_saas_repo: MadeByThePinsHub/infra/docker/custom-cicd-images

jobs:
  sync-commits-main:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Synchorize to GitLab
        uses: wei/git-sync@v3
        with:
          source_repo: ${{github.repository}}
          source_branch: "master"
          destination_repo: "https://RecapTimeBot:${{secrets.GL_SERVICE_ACCOUNT_API_KEY}}@gitlab.com/${{env.gitlab_saas_repo}}"
          destination_branch: "master"
